Brain-WP/BrainMonkey

src/Monkey/Functions.php
This pull request includes two new `Functions` methods `justEcho()` and `echoArg()` that allow for mocking echoing functions (in WordPress context, for example any of the `*_e()` functions). These have been realized by extending the _returning_ methods.
If something's not right, just let me know.
=> Add echoing functions.

composer.json
With PHP version in the requirements composer can handle warnings on platforms below this version. Further the 'requires' section on packagist.org gives a quick information about this.
=> Add php 5.4.0 to composer.json requirements

src/Monkey/Functions.php
When mocking a fully-qualified (namespaced) function, the `::check()` method fails because the first element in the array is an empty string. Removing a potential leading slash fixes this. Right? :)
=> Remove leading slash.

docs/functions-bulk.md
Not addressed - the typo in the docs and method name:
`bulkDefinePassTrough` ❎ 
`bulkDefinePassThrough` ✅
=> Docs: bulk functions improved English

src/Name/ClosureParamStringForm.php
(Replacement for PR #56)
`ReflectionType::__toString()` has been deprecated as of PHP 7.1, though PHP only started throwing warnings about this in PHP 7.4.
This PR changes the parameter type retrieval code in a way that it is compatible with all PHP 7 versions.
Also see:
* https://www.php.net/manual/en/reflectionparameter.gettype.php
=> PHPCompatibility fix: `ReflectionType::__toString()` is deprecated

src/Name/ClosureStringForm.php
`implode()` takes two parameters, `$glue` and `$pieces`.
For historical reasons, `implode()` accepted these parameters in either order, though it was recommended to use the documented argument order of `implode( $glue, $pieces )`.
PHP 7.4 deprecates the tolerance for passing the parameters for `implode()` in reverse order.
PHP 8.0 is expected to remove the tolerance for this completely.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix
* https://php.net/manual/en/function.implode.php
=> PHP 7.4 compatibility fix / implode argument order

tests/cases/functional/ActionsTest.php, tests/cases/functional/FiltersTest.php, tests/cases/functional/FunctionsTest.php, tests/cases/unit/Api/AddActionTest.php, tests/cases/unit/Api/DoActionTest.php
Add import `use` statements for the unit test classes being extended.
=> Tests: minor clean up

composer.json, phpunit.xml.dist, tests/bootstrap.php, tests/cases/unit/Api/FunctionsTest.php, tests/src/FunctionalTestCase.php, tests/src/UnitTestCase.php
* PHPUnit 6 changed the PHPUnit classes to namespaced.
As of PHPUnit 5.4 a compatibility layer is available which aliases most of the old names to the new names.
As the previously required PHPUnit version was already higher than PHPUnit 5.4, switching over to the new class names makes the tests compatible with both PHPUnit 5 as well as 6.
* Unfortunately, the PHPUnit `PHPUnit_Framework_Error` class was not included in the compatibility layer, so to still be able to use that class cross-version, a `class_alias`-es needs to be put in place.
This is done by adding a PHPUnit `bootstrap.php` file, adding that file to the `phpunit.xml.dist` config and having that file require the Composer `autoload.php` file as well as create the necessary class alias for the PHPUnit class.
_As this BrainMonkey …
=> Tests: make testsuite compatible with more recent PHPUnit versions

.travis.yml
While Travis (still) doesn't have an official PHP 7.4 image, this unofficial image made available by one of the PHP core contributors is up-to-date and allows you to test against PHP 7.4.
As PHP 7.4 is supposed to be released by end of November, I'm not setting `allow_failures` as the code really should be compatible before that time, especially **_as other software is depending on BrainMonkey to be able to assess their own PHP 7.4 readiness..._**
The build for this PR won't pass until PR #55 and PR #61 have both been merged.
A passing build containing this commit + the commits of the above mentioned PRs can be found here: https://travis-ci.org/jrfnl/BrainMonkey/builds/596457760
=> Travis: test against PHP 7.4

.travis.yml, composer.json, inc/wp-helper-functions.php
* Installs the [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) package to check code for cross-version compatibility using static analysis based on [PHP_CodeSniffer](https://github.com/squizlabs/php_codesniffer/).
* Includes installing the [DealerDirect Composer PHPCS plugin](https://github.com/Dealerdirect/phpcodesniffer-composer-installer/) which will automatically handle registering the external PHPCompatibility standard with PHP_CodeSniffer.
* Includes adding a Composer script to run the command easily with the correct command-line arguments.
Alternatively, the configuration could be setup in a `phpcs.xml.dist` file which could at a later time be expanded to also include code style rules.
_**Let me know if you'd prefer that.**_
- Note: using `@php` will make …
=> Travis: add task to check the PHP files for cross-version compatibility issues

inc/wp-hook-functions.php, tests/cases/functional/ActionsTest.php, tests/cases/functional/FiltersTest.php
Function set completeness.
This allows for calls to `do_action_deprecated()` and `apply_filters_deprecated()` to be registered and expectations set for these.
This does not include testing that the deprecation notices are being thrown correctly, but as that's WP Core functionality, that shouldn't be tested here anyway.
Refs:
* https://developer.wordpress.org/reference/functions/do_action_deprecated/
* https://developer.wordpress.org/reference/functions/apply_filters_deprecated/
=> Add function stubs for deprecated hook calls

.gitignore, .travis.yml, composer.json, tests/cases/unit/Api/FunctionsTest.php, tests/cases/unit/Expectation/Exception/ExpectationArgsRequiredTest.php, tests/src/FunctionalTestCase.php, tests/src/UnitTestCase.php
Made the most minimal changes to allow the tests to run on PHPUnit 8 and 9.
PHPUnit 9.3 is the first version which is officially compatible with the upcoming PHP 8 release, so now the tests can be run on PHP 8 to confirm that BrainMonkey is compatible with PHP 8 (at this time).
Having confirmed this, allows for packages which use the BrainMonkey package to test their code, to be confident to start testing their own code on PHP 8.
In PHPUnit 8.x, the `setUpBeforeClass()`, `tearDownAfterClass()`, `setUp()` and `tearDown()` methods have received type declarations,with a return type `void`, making it neigh impossible to implement this in a cross-version manner as the `void` return type is not available until PHP 7.1.
However, PHPUnit also supports `@beforeClass`, `@afterClass`, `@before` and …
=> Tests: PHPUnit cross-version compatibility + test against PHP 8

inc/api.php, src/Hook/HookStorage.php, tests/cases/unit/Api/AddFiltersTest.php
Accordingly to WordPress the aforementioned functions has to
return the priority value when the callback function is given.
If the PR get merged it will introduce a new method in `HookStorage` named `hookPriority` which allow to retrieve the priority of an hook by the given `type`, `hookName` and `callback`.
The `has_filter` and `has_hook` will make use of the method only if the `callback` parameter has been given, otherwise will continue to call `isHookAdded`.
The Method `HookStorage::hookPriority` explicitly does not cover the case where a different value other than `string` or `CallbackStringForm` has been passed, so that the developer is notified about the violation but it will try to convert a string into a `CallbackStringForm` instance for convenience.
The method returns the …
=> `has_filter` and `has_action` should returns the priority

docs/functions-testing-tools/function-stubs.md, inc/api.php, tests/cases/unit/Api/FunctionsTest.php
Along the same lines as the other translation functions stubs, this returns the original text unchanged.
Refs:
* https://developer.wordpress.org/reference/functions/_n/
* https://developer.wordpress.org/reference/functions/_nx/
=> WP: stub the `_n()` and `_nx()` functions

docs/wordpress-specific-tools/wordpress-tools.md, inc/wp-helper-functions.php
Simply `trailingslashit` without further ado.
Includes adding the new stub to the documentation.
Excludes tests as I couldn't find tests for the other functions in this file, so it is unclear to me where to add them.
Ref: https://developer.wordpress.org/reference/functions/user_trailingslashit/
Simply `json_encode()` without further ado.
Includes adding the new stub to the documentation.
Excludes tests as I couldn't find tests for the other functions in this file, so it is unclear to me where to add them.
Ref: https://developer.wordpress.org/reference/functions/wp_json_encode/
---
Related to #81
=> WP helper functions: stub user_trailingslashit() and wp_json_encode()

docs/functions-testing-tools/function-stubs.md, inc/api.php, src/Expectation/EscapeHelper.php, tests/cases/unit/Api/FunctionsTest.php
WP 5.5 introduced a new escaping function `esc_xml()`.
This largely stubs that function, except for some real edge cases.
Tests based on the tests used in WP Core.
Ref: https://developer.wordpress.org/reference/functions/esc_xml/
=> WP: stub the `esc_xml()` function

docs/wordpress-specific-tools/wordpress-tools.md
The WordPress specific `stubEscapeFunctions()` and `stubTranslationFunctions()` tools are mentioned in the "Bulk patching with stubs()" section, but not in the WordPress specific tools section.
This attempts to make these (very useful) functions more discoverable by adding links to the "Bulk patching with stubs()" section from the "WordPress testing tools" section.
=> Docs: add x-links for WP stubs

docs/functions-testing-tools/function-stubs.md
Looking at the `Brain\Monkey\Functions\stubTranslationFunctions()` function, the `_e()` and `_ex()` functions are actually also stubbed.
https://github.com/Brain-WP/BrainMonkey/blob/dbb41d3e56d7a768c7f44f909f428d1503f82106/inc/api.php#L134-L157
=> Docs: add more functions missing from lists

inc/api.php
Сlearer return type for \Brain\Monkey\Filters\has function.
=> PHPDoc improvement

tests/cases/unit/Name/ClosureParamStringFormTest.php
This fixes the [broken test](https://github.com/Brain-WP/BrainMonkey/runs/2123646454?check_suite_focus=true) introduced in #95, mentioned in https://github.com/Brain-WP/BrainMonkey/issues/94#issuecomment-800439111.
=> Delete (new) unit test for PHP 5.6

.github/workflows/php-qa.yml
The first alpha of PHP 8.1 has been released, so now seems like a good time to start running the tests against PHP 8.1.
For now, I've configured it to allow builds against PHP 8.1 to fail, while PHP 8.1 is still unstable.
Also: PHPUnit doesn't officially support PHP 8.1 yet, so to install PHPUnit 9.x on PHP 8.1, we need to use `--ignore-platform-reqs`, as otherwise PHPUnit 4.8 would be installed (last PHPUnit version without strict PHP version constraints).
---
**Edit**: I've added a second commit to this PR.
Turns out the default setting for `error_reporting` used by the SetupPHP action is `error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT` and `display_errors` is set to `Off`.
For the purposes of CI, I'd recommend running with `E_ALL` and `display_errors=On` to ensure **all** PHP …
=> GH Actions: start testing against PHP 8.1

.github/workflows/php-qa.yml
I was looking through the action output and was a bit confused by the test runs on PHP >= 7.3 not showing any run information.
Turns out, the tests haven't been running on PHP > 7.3 since October last year, as the `--migrate-configuration` CLI argument is supposed to be used as a stand-alone command and does not trigger a test run after the migration has finished....
Fixed now.
Note: this now exposes quite a lot of problems on PHP 8.1, some in Patchwork, some in Mockery. I'm especially concerned about the issues in Patchwork as the last commit to that repo was in 2019.
=> GH Actions: run the tests on PHP >= 7.3

src/Name/ClosureParamStringForm.php, tests/cases/unit/Name/ClosureParamStringFormTest.php, tests/cases/unit/Name/ClosureStringFormTest.php
This commit makes the `ClosureParamStringForm` class compatible with PHP 5.6, both for the `fromString()`, as well as the `fromReflectionParameter()` method.
In PHP 5.6, to retrieve the type, typically a pattern along the following lines would be used:
```php
try {
$hasType = $reflParameter->getClass();
} catch ( ReflectionException $e ) {
// Class with a type declaration for a non-existent class.
}
$typeName = $hasType->name;
```
The downside of the above is that the `ReflectionParameter::getClass()` method triggers an autoload of the class (for class-based type declarations).
See: https://www.php.net/manual/en/reflectionparameter.getclass.php#108620
In a test situation, this autoload should not be triggered by the tests, so instead of this pattern, the …
=> Make the `ClosureParamStringForm` class compatible with PHP 5.6

composer.json
Patchwork 2.1.13 has just been released and includes improved PHP 8.0 support and fixes for PHP 8.1 support.
I'd recommend making this the new minimum supported version for Patchwork.
Ref: https://github.com/antecedent/patchwork/releases
=> Composer: update the minimum version requirement for Patchwork

tests/cases/functional/FunctionsTest.php
In this particular test the `is_wp_error()` function is being aliased to the PHP native `ctype_alpha()` function, but that function expects to be passed a string, while the second test was passing an integer.
By changing the type of the value passed, but keeping the value the same, this PHP 8.1 deprecation notice is avoided.
Fixes the following test failure as per https://github.com/Brain-WP/BrainMonkey/issues/103#issuecomment-927148428
```
Brain\Monkey\Tests\Functional\FunctionsTest::testReDefinePredefinedStubsWithWhen
ctype_alpha(): Argument of type int will be interpreted as string in the future
/home/runner/work/BrainMonkey/BrainMonkey/vendor/antecedent/patchwork/src/CallRerouting.php:285
/home/runner/work/BrainMonkey/BrainMonkey/vendor/antecedent/patchwork/src/CallRerouting.php:317 …
```
=> PHP 8.1: fix a test

composer.json
The last few releases of Patchwork fixed up more PHP syntax issues and further improve PHP 8.0 and 8.1 compatibility.
Ref: https://github.com/antecedent/patchwork/releases
=> Composer: update minimum supported Patchwork version

composer.json
... to versions which contain PHP 8.1 support.
Ref: https://github.com/mockery/mockery/releases
=> Composer: update version constraints for Mockery

composer.json
As this repo is not a PHPCS standard, there is no need to allow for a range of versions for the `dealerdirect/phpcodesniffer-composer-installer` dependency, so best to use the latest version.
https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases
=> Composer: update dev-dependency constraints

composer.json
**Note:** while BrainMonkey doesn't have a direct, non-dev dependency on PHPUnit, it will generally be used in combination with PHPUnit. So, while I could have updated the `dev` version constraints to only allow for the latest minors of various PHPUnit versions, it seemed more prudent to allow for a liberal range of versions to allow for discovering potential incompatibilities with PHPUnit versions.
While PHPUnit as of version 8.5.12 allows for installation on PHP 8.0, it still contained a [nasty bug](sebastianbergmann/phpunit#4575) which would error out the test run with a Fatal when PHPUnit 8.5.12 would be installed for PHP 8.1.
This bug was fixed in version 8.5.14.
This adjustment of the version constraints means that when `composer install` is run with `--prefer-lowest` on PHP 8.x, …
=> Composer: update PHPUnit version constraints

.github/workflows/php-qa.yml
Follow up on #99: also enable assertions, which are turned off by default when using `setup-php@v2`.
... for faster linting results.
Ref: https://github.com/php-parallel-lint/PHP-Parallel-Lint/
The results of PHP Parallel Lint can also be used in combination with [cs2pr](https://github.com/staabm/annotate-pull-request-from-checkstyle) to show any issues in-line in the GH (PR) code view.
... for faster builds and to be kind to the resources which GH provides freely.
The caching is handled by using a [predefined GH action](https://github.com/marketplace/actions/install-composer-dependencies) specifically created for this purpose.
The alternative would be to handle the caching manually, which would add three extra steps to the script.
Refs:
* …
=> GH Actions: mixed bag of improvements

.github/workflows/php-qa.yml
The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Refs:
* https://github.com/ramsey/composer-install/releases/tag/2.0.0
* https://github.com/ramsey/composer-install/releases/tag/2.0.1
* https://github.com/ramsey/composer-install/releases/tag/2.0.2
=> GH Actions: version update for `ramsey/composer-install`

.github/workflows/php-qa.yml
A while back the `codecov/codecov-action` released a new major.
As per the release notes:
> On February 1, 2022, the v1 uploader will be full sunset and no longer function. This is due to the deprecation of the underlying bash uploader. This version uses the new uploader.
Considering Feb 2022 is creeping closer every day, updating seems prudent.
> Multiple fields have not been transferred from the bash uploader or have been deprecated. Notably many of the `functionalities` and `gcov_` arguments have been removed.
This repo does not seem to be affected by this.
Refs:
* https://github.com/codecov/codecov-action/releases/tag/v2.0.0
* https://github.com/codecov/codecov-action/releases/tag/v2.0.1
* https://github.com/codecov/codecov-action/releases/tag/v2.0.2
* …
=> GH Actions: version update for `codecov/codecov-action`

.github/workflows/php-qa.yml
Yet another predefined action has had a major release.
This is, again, mostly just a change of the Node version used by the action itself (from Node 12 to Node 16).
Refs:
* https://github.com/codecov/codecov-action/releases
=> GH Actions: version update for codecov action runner

.github/workflows/php-qa.yml
Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like `8.1.11`.
> * The options passed via `composer-options`.
> * The dependency version setting as per `dependency-versions`.
> * The working directory as per `working-directory`.
> * A hash of the `composer.json` and/or `composer.lock` files.
This means that aside from other factors, the cache will always be busted when changes are made to the (committed) `composer.json` or the …
=> GH Actions: bust the cache semi-regularly

docs/wordpress-specific-tools/wordpress-tools.md, inc/wp-helper-functions.php, tests/cases/functional/FunctionsTest.php
Add stubs for `wp_validate_boolean()` and `wp_slash()`.
See #125
=> Predefined functions enhancements

docs/functions-testing-tools/function-stubs.md, inc/api.php
Stub for `_n_noop()`, `_nx_noop()`, and `translate_nooped_plural()` were missing in `stubTranslationFunctions()`
See #51
=> Stub _n_noop, _nx_noop, translate_nooped_plural

src/Expectation/Expectation.php
PHP 8.4 deprecates implicitly nullable parameters, i.e. typed parameter with a `null` default value, which are not explicitly declared as nullable.
This commit fixes the one instance found in this codebase.
Includes updating the documentation to match.
Note: while this is not a `final` class and the change is effectively a change to the method signature, this is not a BC break as (overloaded) constructors are exempt from signature checks.
Ref: https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
=> PHP 8.4 | Fix implicitly nullable parameter

src/Expectation/Exception/MissingFunctionExpectations.php, src/Expectation/FunctionStub.php, tests/cases/unit/Api/FunctionsTest.php
PHP 8.4 deprecates passing `E_USER_ERROR` to `trigger_error()`, with the recommendation being to replace these type of calls with either an Exception or an `exit` statement.
This commit fixes the one instance found in this codebase by introducing a new `MissingFunctionExpectations` exception.
Includes updating the related tests (and test names) to match.
Ref: https://wiki.php.net/rfc/deprecations_php_8_4#deprecate_passing_e_user_error_to_trigger_error
Related to #146
=> PHP 8.4 | Fix passing `E_USER_ERROR` to `trigger_error()`

.github/workflows/php-qa.yml
* Builds against PHP 8.4 are no longer allowed to fail.
* Add _allowed to fail_ build against PHP 8.5.
Note: running PHP 8.4 with `dependencies: lowest` will not work due to issues in Patchwork and Mockery, but raising the minimum versions of those dependencies would require dropping support for PHP < 7.1 (and maybe more).
Ref: https://www.php.net/releases/8.4/en.php
=> GH Actions: PHP 8.4 has been released

composer.json
... for which the 1.0 version was released over two years ago.
Refs:
* https://github.com/PHPCSStandards/composer-installer/releases/tag/v1.0.0
=> Composer: update the PHPCS Composer installer
